# @package eval

evaluation:
  environments:
    - name: "FastSnake-Default-StateVisitation"
      n_rollouts: 400
      episode_length: 8
      generation:
        temperature: 1.25
        top_p: 1.0
        top_k: -1
        min_p: 0.0
        do_sample: False
      initial_seed: 10 # Use a fixed seed for reproducibility
      seed_group_size: 20
      freeze_completed_episodes: True
      duplication_mode: none
      env_name: fastsnake
      task: none
      format_penalty: 0.0
      instruction_prompt: | 
        [Instructions]
        You are a helpful assistant. You always respond by wrapping your thoughts in the correct XML tags. Your maximum response length: 200 words (tokens)
        You are controlling a snake in a multi-player Snake game

        [Available Actions]
        "up": move your head one space up,
        "down": move your head one space down,
        "left": move your head one space left,
        "right": move your head one space right,

        [Rules]
        - You can move your head one space up, down, left, or right
        - If you move onto an apple, you get 1 point and you gain a body segment
        - You die if you move into a wall, another snake, or yourself
      captioner:
        type: naive
        max_text_history: 0
      fastsnake_kwargs:
        width: 10
        height: 10
        max_rounds: 8
        num_external_snakes: 1
        num_random_snakes: 0
        death_reward: -1
        step_reward: 0
        no_respawn: true # No random elements to ensure deterministic environment behavior
        print_visualization: false