# @package eval

evaluation:
  environments:
    - name: "WebShop-10k"
      n_rollouts: 100  
      episode_length: 16
      initial_seed: 0 
      freeze_completed_episodes: True
      duplication_mode: none
      env_name: webshop
      format_penalty: 0.0
      binary_reward: False
      captioner:
        type: naive
        max_text_history: 0
      webshop_kwargs:
        max_steps: 16
        goals_seed: 0
        num_products: 10_000
    - name: "WebShop-100k"
      n_rollouts: 50  
      episode_length: 16
      initial_seed: 0 
      freeze_completed_episodes: True
      duplication_mode: none
      env_name: webshop
      format_penalty: 0.0
      binary_reward: False
      captioner:
        type: naive
        max_text_history: 0
      webshop_kwargs:
        max_steps: 16
        goals_seed: 0
        num_products: 100_000